[tool.poetry]
name = "shopping-list-generator"
version = "0.1.0"
description = ""
authors = ["Calum Andrew Morrell <calum@drulum.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
